### ISSUE TITLE
The published message contains wrong start_time

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/pytroll-cspp-runner#3]
Here the `start_time` and `end_time`

https://github.com/pytroll/pytroll-cspp-runner/blob/master/bin/viirs_dr_runner.py#L353

are parsed from the filename which is the last fle in the file list a few lines above?

This gives not the expected `start_time` in the published message

**Comment by gerritholl** [comment]
Some more details to this, a case study:

The CSPP runner is processing a file that covers 13:42:52 - 13:55:40.  CSPP spews out files that cover 13:42:52 - 13:44:17, 13:44:18 - 13:45:30, 13:45:44 - 13:47:07, 13:47:08 - 13:48:32, 13:48:34 - 13:49:58, 13:49:59 - 13:51:24, 13:51:25 - 13:52:48, 13:52:49 - 13:54:14, and 13:54:15 - 13:55:39.  When the CSPP runner is finished, it sends a posttroll message with start_time 13:54:15, end time 13:55:39, but still containing all the files that belong to the overpass.

I don't have a MCVE (yet), but it's happening all the time in production:

```
[INFO: 2021-12-29 14:13:47 : cspp_runner.runner] RDR to SDR processing on npp/viirs with CSPP start! Start time = 2021-12-29 13:42:52
[DEBUG: 2021-12-29 14:13:47 : cspp_runner.runner] Set the start time of the entire swath: 2021-12-29 13:42:52
[INFO: 2021-12-29 14:13:47 : cspp_runner.runner] Start time: 2021-12-29 13:42:52
[DEBUG: 2021-12-29 14:13:47 : cspp_runner.runner] Sent message to run: pytroll://file/noaa20/viirs/direktempfang file pytroll@oflks333.dwd.de 2021-12-29T14:04:16.062519 v1.01 application/json {"path": "", "start_time": "2021-12-29T13:42:52", "end_time": "2021-12-29T13:55:40.200000", "processing_time": "2021-12-29T13:55:49.296000", "uri": "/data/pytroll/IN/NOAA20/RNSCA-RVIRS_j01_d20211229_t1342520_e1355402_b00001_c20211229135549296000_all-_dev.h5", "uid": "RNSCA-RVIRS_j01_d20211229_t1342520_e1355402_b00001_c20211229135549296000_all-_dev.h5", "sensor": ["viirs"], "platform_name": "NOAA-20", "orbit_number": "00001"}
[DEBUG: 2021-12-29 14:13:47 : cspp_runner.runner] Received message data = {'path': '', 'start_time': datetime.datetime(2021, 12, 29, 13, 42, 52), 'end_time': datetime.datetime(2021, 12, 29, 13, 55, 40, 200000), 'processing_time': datetime.datetime(2021, 12, 29, 13, 55, 49, 296000), 'uri': '/data/pytroll/IN/NOAA20/RNSCA-RVIRS_j01_d20211229_t1342520_e1355402_b00001_c20211229135549296000_all-_dev.h5', 'uid': 'RNSCA-RVIRS_j01_d20211229_t1342520_e1355402_b00001_c20211229135549296000_all-_dev.h5', 'sensor': ['viirs'], 'platform_name': 'NOAA-20', 'orbit_number': '00001'}
[DEBUG: 2021-12-29 14:26:24 : cspp_runner.runner] sending: pytroll://collection/viirs/SDR/1B/dwd/devel/polar/direct_readout dataset pytroll@oflks333.dwd.de 2021-12-29T14:26:24.974689 v1.01 application/json {"path": "", "start_time": "2021-12-29T13:54:15.200000", "end_time": "2021-12-29T13:55:39.700000",
```
(last message truncated for brevity, as the actual message is about 75k long)

This is a serious problem, because it means trollflow2 gets the wrong start time.  This time of year, when we have a northbound overpass during the day, the last granule in the overpass is somewhere near the Arctic Circle.  Therefore, the `check_sunlight_coverage` check throws out products that need daylight during any time of day.
